### ISSUE TITLE
Server Side Render failed

### ISSUE THREAD

**Issue by housten0219** [summernote/react-summernote#45]
I try use @StanleySong [solution(),](https://github.com/summernote/react-summernote/issues/12) But i get another error
`$node.attr(...).tooltip is not a function
TypeError: $node.attr(...).tooltip is not a function
at http://localhost:3002/_next/-/page/blog-release.js:89923:10
at Renderer.render (node_modules/react-summernote/dist/react-summernote.js:11815:0)
at http://localhost:3002/_next/-/page/blog-release.js:89867:17
at Array.forEach ()
at Renderer.render (node_modules/react-summernote/dist/react-summernote.js:11809:0)
at http://localhost:3002/_next/-/page/blog-release.js:93252:12
at Buttons.build (node_modules/react-summernote/dist/react-summernote.js:15688:0)
at Context.invoke (node_modules/react-summernote/dist/react-summernote.js:11736:0)
at Toolbar.initialize (node_modules/react-summernote/dist/react-summernote.js:15820:0)
at Context.initializeModule (node_modules/react-summernote/dist/react-summernote.js:11665:0)

in ReactSummernote (at ContentField.js:63)
in div (at ContentField.js:61)
in ContentField (at BlogReleaseLayout.js:88)
in form (at BlogReleaseLayout.js:64)
in div (at BlogReleaseLayout.js:63)
in div (at BlogReleaseLayout.js:62)
in div (at BlogReleaseLayout.js:60)
in div (at BlogReleaseLayout.js:58)
in div (at Layout.js:6)
in Layout (at BlogReleaseLayout.js:55)
in BlogReleaseLayout (at blog-release.js:385)
in BlogReleaseController (created by withRouter(BlogReleaseController))
in withRouter(BlogReleaseController) (created by App)
in Container (created by App)
in App
in AppContainer`
Who can help me?

**Comment by AshishKapoor** [comment]
Any updates?

**Comment by StanleySong** [comment]
did you take a look at this? 
https://github.com/summernote/summernote/issues/2157
