### ISSUE TITLE
navigator not found

### ISSUE THREAD

**Issue by ollietjc** [summernote/react-summernote#59]
navigator is not defined
ReferenceError: navigator is not defined
    at Object.<anonymous> (F:\Projects\ollietjccom\node_modules\react-summernote\dist\react-summernote.js:10309:19)
    at F:\Projects\ollietjccom\node_modules\react-summernote\dist\react-summernote.js:9913:37
    at Object.<anonymous> (F:\Projects\ollietjccom\node_modules\react-summernote\dist\react-summernote.js:9922:2)
    at __webpack_require__ (F:\Projects\ollietjccom\node_modules\react-summernote\dist\react-summernote.js:30:30)
    at Object.<anonymous> (F:\Projects\ollietjccom\node_modules\react-summernote\dist\react-summernote.js:16970:1)
    at Object.<anonymous> (F:\Projects\ollietjccom\node_modules\react-summernote\dist\react-summernote.js:17236:30)
    at __webpack_require__ (F:\Projects\ollietjccom\node_modules\react-summernote\dist\react-summernote.js:30:30)
    at F:\Projects\ollietjccom\node_modules\react-summernote\dist\react-summernote.js:76:18
    at F:\Projects\ollietjccom\node_modules\react-summernote\dist\react-summernote.js:79:10
    at webpackUniversalModuleDefinition (F:\Projects\ollietjccom\node_modules\react-summernote\dist\react-summernote.js:3:20)
    at Object.<anonymous> (F:\Projects\ollietjccom\node_modules\react-summernote\dist\react-summernote.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)

Used with Next.js SSR this error came up.

Tried rendering ReactSummernote client side but doesn't work as well..

Anyone had this problem?

**Comment by timknapp12** [comment]
@ollietjc , yes I am using nextjs and just got the same error
